# Generated by Django 5.2.5 on 2025-08-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_unit_remove_book_category_product'),
        ('userapp', '0003_remove_cartitem_book_remove_orderitem_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
