# Generated by Django 5.2.5 on 2025-09-05 07:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subquantity_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductSubQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('factor_to_base', models.DecimalField(decimal_places=6, default=Decimal('0.001'), max_digits=12)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquantities', to='adminapp.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
