# Generated by Django 5.2.5 on 2025-09-06 04:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_product_subquantity_enabled_productsubquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('factor_to_base', models.DecimalField(decimal_places=6, default=Decimal('0.001'), max_digits=12)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunits', to='adminapp.unit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('unit', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productsubquantity',
            name='unit_subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='adminapp.unitsubunit'),
        ),
    ]
