# Generated by Django 5.2.5 on 2025-09-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_unitsubunit_productsubquantity_unit_subunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
