# Generated by Django 5.2.5 on 2025-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_order_order_number_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('transit', 'In Transit'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
