# Generated by Django 5.2.5 on 2025-08-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_offer_alter_category_description_and_more'),
        ('userapp', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
            preserve_default=False,
        ),
    ]
